name: nucleo_dart
description: Bindings to the nucleo rust library
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  code_assets: any
  hooks: any
  logging: ^1.3.0
  native_toolchain_rust: 0.1.0-dev.7

dev_dependencies:
  ffigen: 20.0.0-dev.0
  lints: ^6.0.0
  test: ^1.25.15
